name = "profit-calc-proxy"
main = "index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量（Fixer API Key 和 固定API密钥）
[vars]
FIXER_API_KEY = "vrbrAqx7SGXVgjF1lPufV6G86hzqZ0PE"
API_KEY = "fixed_api_key_123456"

# KV命名空间绑定
[[kv_namespaces]]
binding = "PROFIT_CALC_KV"
id = "01304a50e05d451682ca6b7b22a1b65d"
# preview_id = "ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT"

[[triggers]]
cron = ["0 0 * * *"] # 每天UTC时间0点执行（北京时间上午8点）

[observability]
enabled = true